sonar.projectKey=qa-fullcycle-portfolio
sonar.projectName=QA Fullcycle Portfolio
sonar.host.url=http://host.docker.internal:9000

sonar.sources=app/src,app/public
sonar.tests=app/src,tests
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/test-results/**,**/playwright-report/**

sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
sonar.sourceEncoding=UTF-8
